### PR TITLE
BST-5085: add tfsgit support

### PR DESCRIPTION
**Pull request by JonathanSerafini**
Update the extension to support tfsgit repositories.
Additionally we update the azure pipeline with an explicit checkout step to persist credentials in tfsgit

### CODE REVIEW

**Review by Clearedkinkajou — APPROVED** [review]
Is TfsGit to support both TF and Git in Azure DevOps, or just one of them?
image

**Comment by JonathanSerafini** [comment]
this is specifically for "tf git"

**Comment by Clearedkinkajou** [comment]
> this is specifically for "tf git"

Okay I get it, it's just a cli tool to work with Git repositories in TFS and Azure DevOps Server

**Review by lindycoder — APPROVED** [review]
Thanks for the doc update!

**Comment by JonathanSerafini** [comment]
rebased on latest

**Review by Clearedkinkajou — APPROVED** [review]

**Pull request merged**
